project_name: project_name # for wandb
exp_name: baseline # experiment name

exp: ${exp_name}_${now_dir}

model_name: efficientnet_b0 # models from timm - https://huggingface.co/docs/timm/en/models/

train:
  root: /path # project root with dataset and outputs
  pretrained: True

  data_path: ${train.root}/data/dataset # path to dataset
  path_to_test_data: ${train.root}/data/to_test # path to test data used infer
  path_to_save: ${train.root}/output/models/${exp} # where to save output

  debug_img_path: ${train.root}/output/debug_images
  eval_preds_path: ${train.root}/output/eval_preds
  bench_img_path: ${train.root}/output/bench_imgs
  infer_path: ${train.root}/output/infer
  visualized_path: ${train.root}/output/visualized

  ### Configs ###
  use_wandb: True
  device: cuda

  label_to_name: # dataset's classes
    0: "class_1"
    1: "class_2"
    2: "class_3"

  img_size: [256, 256] # (h, w)
  to_visualize_eval: True # save images with gt and preds
  debug_img_processing: True # save images after preprocessing

  amp_enabled: True # use automatic mixed precision
  clip_max_norm: 1.0 # gradient clipping

  batch_size: 64 # physical, should fit on the device
  b_accum_steps: 1 # grad accumulation (n * bs)
  epochs: 15
  label_smoothing: 0.1
  layers_to_train: -1
  early_stopping: 0 # 0 - no early stopping
  num_workers: 12

  ### EMA ###
  use_ema: False # use exponential moving average model
  ema_momentum: 0.9998

  ### Optimizer and Scheduler ###
  base_lr: 0.0001
  cycler_pct_start: 0.1
  weight_decay: 0.0001
  betas: [0.9, 0.999]

  ### Augs ###
  augs:
    multiscale_prob: 0.0
    rotate_90: 0.3
    left_right_flip: 0.3
    up_down_flip: 0.2
    to_gray: 0
    blur: 0
    gamma: 0
    brightness: 0.01
    noise: 0

  seed: 42
  cudnn_fixed: True


split:
  shuffle: True
  train_split: 0.8
  val_split: 0.1 # test_split = 1 - train_split - val_split


export: # TensorRT must be done on the inference device
  half: False
  max_batch_size: 1


### service ###
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

now_dir: &nowdir ${now:%Y-%m-%d}
