project_name: project_name
exp_name: baseline

exp: ${exp_name}_${now_dir}

train:
  root: /path/to.progect
  device: cuda

  label_to_name: {0: "class_1", 1: "class_2", 2: "class_3"}
  img_size: [256, 256] # (h, w)

  train_split: 0.8
  val_split: 0.1

  batch_size: 64
  epochs: 15
  use_scheduler: True

  layers_to_train: -1

  num_workers: 10
  threads_to_use: 10

  data_path: ${train.root}/dataset
  path_to_save: ${train.root}/output/models/${exp}

  seed: 42
  cudnn_fixed: False
  debug_img_processing: False


export:
  trt: True # must be done on inference device
  trt_half: False
  max_batch_size: 1

  model_path: ${train.path_to_save}
  path_to_data: ${train.root}/to_test
  vis_path: ${train.root}/output/visualized



### service ###
defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

now_dir: &nowdir ${now:%Y-%m-%d}
